#!/bin/bash -f

source activate astroconda

SEDMPATH=$HOME/kpy

if [ -z ${PYTHONPATH+X} ]
then PYTHONPATH=${PYTHONPATH}:${SEDMPATH}
else
    PYTHONPATH=${SEDMPATH}
fi
export PYTHONPATH

if [ "$#" -eq 0 ]
then 
    echo "Starting Python"
    ipython --pylab --colors LightBG
else
    case $1 in
        what) python $SEDMPATH/SEDMr/What.py "$@";;
        roll) python $SEDMPATH/SEDMr/Roller.py "$@";;
        check) shift 1; python $SEDMPATH/SEDMr/Check.py "$@";;
        plan) shift 1; python $SEDMPATH/SEDMr/Plan.py "$@";;
        plan2) shift 1; python $SEDMPATH/SEDMr/Plan2.py "$@";;
        extract) python $SEDMPATH/SEDMr/Extractor.py "$@";;
        specarith) python $SEDMPATH/SEDMr/SpecArith.py "$@";;
        report) python $SEDMPATH/SEDMr/DrpReport.py;;
        effplot) python $SEDMPATH/SEDMr/EffTrend.py;;
        posplot) python $SEDMPATH/SEDMr/PosTrend.py;;
        *) python -u "$@";;
    esac
fi
exit

