#!/bin/csh -f

alias ur_setup 'eval `$HOME/.ureka/ur_setup -csh \!*`'
alias ur_forget 'eval `$HOME/.ureka/ur_forget -csh \!*`'


setenv SEDMPATH $HOME/kpy

if ! $?PYTHONPATH then
    setenv PYTHONPATH ${SEDMPATH}
else
    setenv PYTHONPATH ${PYTHONPATH}:${SEDMPATH}
endif

ur_setup

if ($#argv == 0) then 
    echo "Starting Python"
    ipython --pylab --colors LightBG
else
    switch ( $argv[1] )
        case "move":
            python $SEDMPATH/SEDM/Mover.py $argv[2-]
            breaksw
        case "what":
            python $SEDMPATH/SEDMr/What.py $argv
            breaksw
        case "roll":
            python $SEDMPATH/SEDMr/Roller.py $argv
            breaksw
        case "check":
            python $SEDMPATH/SEDMr/Check.py $argv[2-]
            breaksw
        case "specarith":
            python $SEDMPATH/SEDMr/SpecArith.py $argv[2-]
            breaksw
        case "extract":
            python $SEDMPATH/SEDMr/Extractor.py $argv[2-]
            breaksw
        case "plan":
            python $SEDMPATH/SEDMr/Plan.py ifu*fits
            breaksw
        case "plan2":
            python $SEDMPATH/SEDMr/Plan2.py ifu*fits
            breaksw
        case "report":
            python $SEDMPATH/SEDMr/DrpReport.py
            breaksw
        case "effplot":
            python $SEDMPATH/SEDMr/EffTrend.py
        default
            python -u $*
            breaksw
    endsw
endif

onintr -

    
